# Funding.yml

github: [your-github-username]
patreon: yourpatreonusername
open_collective: your-opencollective-name
ko_fi: yourkofiname
lfx_crowdfunding: your-lfx-crowdfunding-url
custom: https://example.com/donate
