apiVersion: v1
kind: Service
metadata:
  name: cargobay-redis
  namespace: cargobay
spec:
  selector:
    app: cargobay-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cargobay-redis
  namespace: cargobay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cargobay-redis
  template:
    metadata:
      labels:
        app: cargobay-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
